// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw60hJD9COxycx7KcoQNedFR0kKZT7YKY',
    appId: '1:368224353430:web:0a26d2d743894f40e016b7',
    messagingSenderId: '368224353430',
    projectId: 'qoshkopravtosavdo',
    authDomain: 'qoshkopravtosavdo.firebaseapp.com',
    storageBucket: 'qoshkopravtosavdo.appspot.com',
    measurementId: 'G-ZH79Q1VHEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4tYaCAnKPAC1U8RkgyhcTYlj1Ay9WaFg',
    appId: '1:368224353430:android:43a1c9be76f93398e016b7',
    messagingSenderId: '368224353430',
    projectId: 'qoshkopravtosavdo',
    storageBucket: 'qoshkopravtosavdo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEnXW6BwyWSH3az9v-cgf1zc8mTs-UM8',
    appId: '1:368224353430:ios:c2ba8f50cc41ed88e016b7',
    messagingSenderId: '368224353430',
    projectId: 'qoshkopravtosavdo',
    storageBucket: 'qoshkopravtosavdo.appspot.com',
    iosBundleId: 'dev.bogibek.qas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEnXW6BwyWSH3az9v-cgf1zc8mTs-UM8',
    appId: '1:368224353430:ios:c2ba8f50cc41ed88e016b7',
    messagingSenderId: '368224353430',
    projectId: 'qoshkopravtosavdo',
    storageBucket: 'qoshkopravtosavdo.appspot.com',
    iosBundleId: 'dev.bogibek.qas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw60hJD9COxycx7KcoQNedFR0kKZT7YKY',
    appId: '1:368224353430:web:5d1b8bc1e663dfc9e016b7',
    messagingSenderId: '368224353430',
    projectId: 'qoshkopravtosavdo',
    authDomain: 'qoshkopravtosavdo.firebaseapp.com',
    storageBucket: 'qoshkopravtosavdo.appspot.com',
    measurementId: 'G-JN0S83Y2NT',
  );
}
